---

- name: windows_install | waiting 3 minutes for the server to boot up
  pause:
     minutes=3
     # prompt=".... waiting 3 minutes for the server to boot up ...."


- name: windows_install | Install IIS
  connection: winrm
  win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
  tags:
    - install_iis

- name: windows_install | Download simple web site to 'C:\inetpub\wwwroot\ansible.html'
  connection: winrm
  win_template:
        src: 'index.html'
        dest: 'C:\inetpub\wwwroot\ansible.html'
  notify:
    - restart iis
    - mail confimration module
    # uncomment the above if you want to send a confirmation mail, but don't forget to modify the mail module under roles/internal/handlers/main.yml ;-)
  tags:
    - download_sample_page

#- name: windows_install | Show the user the testing URL
#  debug:
#        msg: 'please open this URL using your browser to see your demo Web Server http://{{ ec2.tagged_instances[0].public_dns_name }}/ansible.html'
